version: '3'

services:
  postgres:
    image: postgres
    environment:
      - "POSTGRES_DB=go_login"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=mysecretpassword"
    ports:
      - "5432:5432"
    volumes:
      - ./.data:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
    driver: bridge

